### ISSUE TITLE
Dropbox

### ISSUE THREAD

**Issue by TechnoColor5** [cmackenzie1/new-grads-2020#25]
This is not really an issue for this repo but is anyone else having issues applying to Dropbox? Everytime I click on "Submit Application" the page scrolls to the top and never submits. I've tried multiple browsers/computers now.

**Comment by cmackenzie1** [comment]
I just submitted one successfully using Chrome. Have you tried using Incognito mode?

**Comment by TechnoColor5** [comment]
Oh it worked on Chrome, weird that it wouldn't work in safari or Firefox. Closing issue
