### ISSUE TITLE
Pinterest New Grad SWEs

### ISSUE THREAD

**Issue by chenghu3** [cmackenzie1/new-grads-2020#74]
https://careers.pinterest.com/careers/details/1730518
https://careers.pinterest.com/careers/details/1852166

**Comment by cmackenzie1** [comment]
can you to make a PR with those changes?

**Comment by chenghu3** [comment]
> can you to make a PR with those changes?

Done, https://github.com/cmackenzie1/new-grads-2020/pull/75
